'use server';

/**
 * Server action for compose generation.
 * Supports two modes:
 * 1. Rule-based (default) — parse compose_hints and generate YAML
 * 2. AI-enhanced (optional) — use OpenAI for complex customization
 */
import { z } from 'zod';

const GenerateComposeSchema = z.object({
  templateSlug: z.string().min(1),
  templateName: z.string().min(1),
  composeHints: z.string().optional(),
  configValues: z.record(z.string(), z.string()),
});

export type GenerateComposeInput = z.infer<typeof GenerateComposeSchema>;

interface GenerateComposeResult {
  success: boolean;
  compose?: string;
  model?: string;
  tokens?: number;
  error?: string;
}

/**
 * Rule-based compose generator — no LLM required.
 * Parses compose_hints and configValues to build a valid docker-compose.yml
 */
function generateComposeFromHints(
  templateName: string,
  templateSlug: string,
  hints: string,
  config: Record<string, string>,
): string {
  const lines: string[] = [];
  
  // Header
  lines.push(`# Docker Compose for ${templateName}`);
  lines.push(`# Generated by AutoSelfHost (ASH)`);
  lines.push('');
  lines.push('version: "3.8"');
  lines.push('');
  lines.push('services:');
  
  // Main service
  const serviceName = templateSlug.replace(/-/g, '_');
  lines.push(`  ${serviceName}:`);
  
  // Extract image from hints
  const imageMatch = hints.match(/Use ([^\s.]+\/[^\s.]+|[^\s.]+:[^\s.]+|[^\s.]+) image/i);
  const image = imageMatch?.[1] ?? `${templateSlug}:latest`;
  lines.push(`    image: ${image}`);
  
  lines.push(`    container_name: ${serviceName}`);
  lines.push(`    restart: unless-stopped`);
  
  // Ports
  const portEntries: string[] = [];
  for (const [key, value] of Object.entries(config)) {
    if (key.includes('port') && value) {
      // Map external port to container port (assume same for simplicity)
      portEntries.push(`      - "${value}:${value}"`);
    }
  }
  if (portEntries.length > 0) {
    lines.push('    ports:');
    lines.push(...portEntries);
  }
  
  // Environment variables
  const envEntries: string[] = [];
  for (const [key, value] of Object.entries(config)) {
    if (!key.includes('port') && !key.includes('path') && value) {
      const envKey = key.toUpperCase();
      envEntries.push(`      ${envKey}: "${value}"`);
    }
  }
  
  // Add common env vars from hints
  if (hints.includes('TZ') || hints.includes('timezone')) {
    const tz = config.timezone ?? 'America/Chicago';
    envEntries.push(`      TZ: "${tz}"`);
  }
  
  if (envEntries.length > 0) {
    lines.push('    environment:');
    lines.push(...envEntries);
  }
  
  // Volumes
  const volumeEntries: string[] = [];
  const namedVolumes: string[] = [];
  
  // Extract volume hints
  const volumeMatches = hints.matchAll(/(?:persistent|volume|mount|data)\s+(?:for\s+)?([^\s.,]+)/gi);
  for (const match of volumeMatches) {
    let path = match[1];
    if (path.startsWith('/')) {
      const volName = `${serviceName}_${path.split('/').filter(Boolean).join('_')}`;
      volumeEntries.push(`      - ${volName}:${path}`);
      namedVolumes.push(volName);
    }
  }
  
  // Add bind mounts for user-specified paths
  for (const [key, value] of Object.entries(config)) {
    if (key.includes('path') && value) {
      volumeEntries.push(`      - ${value}:/data/${key.replace('_path', '')}`);
    }
  }
  
  if (volumeEntries.length > 0) {
    lines.push('    volumes:');
    lines.push(...volumeEntries);
  }
  
  // Network mode (if specified in hints)
  if (hints.includes('network mode host') || hints.includes('network_mode: host')) {
    lines.push('    network_mode: host');
  }
  
  // Capabilities (if specified)
  if (hints.includes('NET_ADMIN')) {
    lines.push('    cap_add:');
    lines.push('      - NET_ADMIN');
    lines.push('      - SYS_MODULE');
  }
  
  // GPU support
  if (hints.includes('GPU') || hints.includes('gpu') || config.gpu === 'true') {
    lines.push('    deploy:');
    lines.push('      resources:');
    lines.push('        reservations:');
    lines.push('          devices:');
    lines.push('            - driver: nvidia');
    lines.push('              count: all');
    lines.push('              capabilities: [gpu]');
  }
  
  // Named volumes section
  if (namedVolumes.length > 0) {
    lines.push('');
    lines.push('volumes:');
    for (const vol of namedVolumes) {
      lines.push(`  ${vol}:`);
    }
  }
  
  return lines.join('\n');
}

/**
 * AI-enhanced compose generator (optional, requires OPENAI_API_KEY).
 */
async function generateComposeWithAI(
  templateName: string,
  hints: string,
  config: Record<string, string>,
): Promise<{ compose?: string; model?: string; tokens?: number; error?: string }> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return { error: 'OpenAI API key not configured for AI mode.' };
  }

  const configLines = Object.entries(config)
    .map(([k, v]) => `- ${k}: ${v}`)
    .join('\n');

  const prompt = `You are a Docker Compose expert. Generate a production-ready docker-compose.yml for ${templateName}.

User configuration:
${configLines}

${hints ? `App requirements:\n${hints}\n` : ''}
Rules:
- Use named volumes (not bind mounts) unless the user specified paths
- Include health checks for critical services
- Set restart: unless-stopped on all services
- Use specific image tags, not :latest
- Include comments explaining non-obvious configuration
- Output ONLY valid YAML, no markdown fencing`;

  const model = process.env.ASH_AI_MODEL ?? 'gpt-4.1-mini';

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: 'system', content: 'You are a Docker Compose expert. Output only valid YAML.' },
          { role: 'user', content: prompt },
        ],
        temperature: 0.3,
        max_tokens: 4096,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      console.error('[ash:generate-compose] OpenAI error:', err);
      return { error: 'AI generation failed. Please try again.' };
    }

    const data = await response.json();
    const compose = data.choices?.[0]?.message?.content?.trim() ?? '';
    const tokens = data.usage?.total_tokens ?? 0;

    if (!compose) {
      return { error: 'AI returned empty response.' };
    }

    // Strip markdown fencing if present
    const cleaned = compose
      .replace(/^```ya?ml\n?/i, '')
      .replace(/\n?```$/i, '')
      .trim();

    return { compose: cleaned, model, tokens };
  } catch (err) {
    console.error('[ash:generate-compose] AI error:', String(err));
    return { error: 'AI generation failed.' };
  }
}

export async function generateCompose(
  input: GenerateComposeInput,
): Promise<GenerateComposeResult> {
  try {
    const parsed = GenerateComposeSchema.parse(input);
    
    // Check if AI mode is explicitly requested
    const useAI = process.env.ASH_USE_AI_COMPOSE === 'true';
    
    if (useAI && process.env.OPENAI_API_KEY) {
      // AI-enhanced mode
      const result = await generateComposeWithAI(
        parsed.templateName,
        parsed.composeHints ?? '',
        parsed.configValues,
      );
      
      if (result.error) {
        // Fallback to rule-based
        const compose = generateComposeFromHints(
          parsed.templateName,
          parsed.templateSlug,
          parsed.composeHints ?? '',
          parsed.configValues,
        );
        return { success: true, compose, model: 'rule-based (AI fallback)' };
      }
      
      return { success: true, ...result };
    }
    
    // Default: Rule-based generation
    const compose = generateComposeFromHints(
      parsed.templateName,
      parsed.templateSlug,
      parsed.composeHints ?? '',
      parsed.configValues,
    );
    
    return { success: true, compose, model: 'rule-based' };
  } catch (err) {
    if (err instanceof z.ZodError) {
      return { success: false, error: err.errors[0]?.message ?? 'Validation failed' };
    }
    console.error('[ash:generate-compose] unexpected error:', String(err));
    return { success: false, error: 'An unexpected error occurred.' };
  }
}
